### ISSUE TITLE
Hello, I've been trying to know what mod keep crashing my world, please help

### ISSUE THREAD

**Issue by CaoTrongThang** [addavriance/EnhancedFallingTrees#6]
I don't know why it keeps randomly crash while playing. Really hope i can get some help

Minecraft version: 1.20.1
Fabric version: 0.16.9
Enhanced Falling Tree version: 0.5.0

java.util.ConcurrentModificationException
    at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
    at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
    at knot//dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:61)
    at knot//com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
    at knot/jdk.proxy2/jdk.proxy2.$Proxy255.render(Unknown Source)
    at knot//net.minecraft.class_757.handler$zpp000$architectury$renderScreenPost(class_757.java:20674)
    at knot//net.minecraft.class_757.method_3192(class_757.java:945)
    at knot//net.minecraft.class_310.method_1523(class_310.java:1219)
    at knot//net.minecraft.class_310.method_1514(class_310.java:802)
    at knot//net.minecraft.client.main.Main.main(Main.java:250)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

logs: https://mclo.gs/bYdpXXj 

Here are the mods work work with Architectury I think
![mods](https://github.com/user-attachments/assets/44fb1778-b805-47b8-bd8b-ef788fcaa4a8)

**Comment by addavriance** [comment]
Are you sure the main problem is with my mod? The crash log doesn't point to it, and the screenshot indicates that you're just missing the Architectury API

**Comment by CaoTrongThang** [comment]
Hey, I'm not good at coding but I've learned about Java a little bit, you should use the ConcurrentHashMap, instead of Hashmap in Java, switching to ConcurrentHashMap is easy. I keep getting concurrentmodificationexception crashin the modpack.

This is your code, hope you can change all the HashMap to ConcurrentHashMap:
package me.adda.enhanced_falling_trees.api;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Optional;
import java.util.function.Supplier;
import net.minecraft.class_2680;
import net.minecraft.class_2960;

public class TreeRegistry {
   private static final Map REGISTRIES = new HashMap();

   public static Supplier register(class_2960 resourceLocation, Supplier treeTypeSupplier) {
      REGISTRIES.put(resourceLocation, (TreeType)treeTypeSupplier.get());
      return treeTypeSupplier;
   }

   public static Optional getTreeType(class_2680 blockState) {
      return REGISTRIES.values().stream().filter((treeType) -> {
         return treeType.enabled() && treeType.mineableBlock(blockState);
      }).findFirst();
   }

   public static Optional getTreeType(class_2960 resourceLocation) {
      return Optional.ofNullable((TreeType)REGISTRIES.get(resourceLocation));
   }

   public static class_2960 getTreeTypeLocation(TreeType treeType) {
      Iterator var1 = REGISTRIES.entrySet().iterator();

      Map.Entry entry;
      do {
         if (!var1.hasNext()) {
            return null;
         }

         entry = (Map.Entry)var1.next();
      } while(entry.getValue() != treeType);

      return (class_2960)entry.getKey();
   }
}

**Comment by addavriance** [comment]
Ah, well, in general this has a place to be, so yes, I'll review it in more detail.

**Comment by addavriance** [comment]
Sorry for the long delay :D, I fixed it in a new commit in the dev branch, I’ll send it for release soon, after the rest of the fixes

**Comment by CaoTrongThang** [comment]
> Sorry for the long delay :D, I fixed it in a new commit in the dev branch, I’ll send it for release soon, after the rest of the fixes

That's great to hear, but any info on the falling trees damage player?

**Comment by addavriance** [comment]
To be honest, I had already considered this before, but little came of it, so I put it off until new releases, so I’ll be doing this right now, along with porting to 1.20.5 - 1.21. I do the development of each mod quite intermittently so as not to burn out, so I switch between languages ​​or projects.

**Comment by CaoTrongThang** [comment]
Some devs stop supporting low popular version, I think you should also do that, maintaining many versions is really hard, your FallingTrees mod just missing that feature I believe

**Comment by addavriance** [comment]
It took a long time, well.

I'll be updating everything to 26.2 soon, bypassing 1.21.11 on Forge due to some mapping issues that couldn't be resolved on either the Architectury Loom or Forge side.
